version: '3'
services:
  db:
    image: postgres:14
    env_file:
      - .env
    networks:
      - rssparser-backend

  app:
    image: ghcr.io/pdf-reports-parser/backend:main
    env_file:
      - .env
    ports:
      - 8000:8080
    networks:
      - rssparser-backend
      - rssparser-frontend

  frontend:
    image: ghcr.io/pdf-reports-parser/frontend:main
    env_file:
      - .env
    ports:
      - 80:5000
    networks:
      - rssparser-frontend

networks:
  rssparser-frontend:
  rssparser-backend: